#import "SlyceBase.h"


NS_ASSUME_NONNULL_BEGIN

typedef NSString *const SlyceLensLocalDetectionMode NS_TYPED_EXTENSIBLE_ENUM;

SLYCE_SDK_EXPORT extern SlyceLensLocalDetectionMode SlyceLensLocalDetectionModeDefault;
SLYCE_SDK_EXPORT extern SlyceLensLocalDetectionMode SlyceLensLocalDetectionModeContinuous;
SLYCE_SDK_EXPORT extern SlyceLensLocalDetectionMode SlyceLensLocalDetectionModeTapToSearch;

NS_ASSUME_NONNULL_END
